// Autogenerated file by run_gen_op.py. Do not edit directly!

#pragma once
#include <ATen/Tensor.h>
#include <ATen/core/function_schema.h>
#include "habana_kernels/lazy_kernels.h"
#include "hpu_ops/hpu_op_helper.h"

namespace habana {


at::Tensor clone(const at::Tensor & self, std::optional<at::MemoryFormat> memory_format);
OUTMETA_DECL(CloneMeta);

}  // namespace habana

