// Autogenerated file by run_gen_op.py. Do not edit directly!

#pragma once
#include <ATen/Tensor.h>
#include <ATen/core/function_schema.h>
#include "habana_kernels/lazy_kernels.h"
#include "hpu_ops/hpu_op_helper.h"

namespace habana {
HPU_OP_BACKEND(MixtureOfExpertsFp8)


at::Tensor mixture_of_experts(const at::Tensor & hidden_states, const at::Tensor & expert_routing_table, const at::Tensor & router_weights, at::TensorList w12, at::TensorList w3, const at::Tensor & d_scale_hidden_states, at::TensorList d_scale_intermediate_hidden_states, at::TensorList d_scale_w12, at::TensorList d_scale_w3, bool permuted_weights, std::string_view activation, int64_t experts_min, int64_t experts_max);
OUTMETA_DECL(MixtureOfExpertsFp8Meta);

}  // namespace habana

