// Autogenerated file by run_gen_op.py. Do not edit directly!

#pragma once
#include <ATen/Tensor.h>
#include <ATen/core/function_schema.h>
#include "habana_kernels/lazy_kernels.h"
#include "hpu_ops/hpu_op_helper.h"

namespace habana {


::std::tuple<at::Tensor,at::Tensor> native_dropout(const at::Tensor & input, double p, std::optional<bool> train);
unsigned NativeDropoutEarlyExitCondition(const at::Tensor & input, double p, std::optional<bool> train);
::std::tuple<at::Tensor,at::Tensor> NativeDropoutEarlyExit(unsigned eePath, const at::Tensor & input, double p, std::optional<bool> train);
OUTMETA_DECL(FusedNativeDropoutMeta);
FILL_PARAMS_DECL(FillFusedNativeDropoutParams);

}  // namespace habana

