// Autogenerated file by run_gen_op.py. Do not edit directly!

#pragma once
#include <torch/library.h>
#include <c10/core/ScalarType.h>
#include <torch/csrc/autograd/custom_function.h>

using namespace at;

namespace habana {


class CastToFp8V2Function
    : public torch::autograd::Function<CastToFp8V2Function> {
 public:
  static std::vector<at::Tensor> forward(
      torch::autograd::AutogradContext* ctx,
      const at::Tensor & input,
	  const ::std::optional<at::Tensor> & scale,
	  bool stochastic_rounding,
	  bool is_amax,
	  at::ScalarType dtype,
	  at::OptionalIntArrayRef scale_shape);
  static std::vector<at::Tensor> backward(
      torch::autograd::AutogradContext* ctx,
      const std::vector<at::Tensor>& grads);
};

::std::tuple<at::Tensor,at::Tensor> cast_to_fp8_v2_dispatch(
	const at::Tensor & input,
	const ::std::optional<at::Tensor> & scale,
	bool stochastic_rounding,
	bool is_amax,
	at::ScalarType dtype,
	at::OptionalIntArrayRef scale_shape);


} // namespace habana

