// Autogenerated file by run_gen_op.py. Do not edit directly!

#include "hpu_ops/op_logger.h"
#include "habana_helpers/logging.h"
#include "common/dump_args.h"
#include <torch/torch.h>
#include "autograd_ops.h"

namespace habana {

using namespace at;

::std::tuple<at::Tensor,at::Tensor> cast_to_fp8_v2_autograd(
	const at::Tensor & input,
	const ::std::optional<at::Tensor> & scale,
	bool stochastic_rounding,
	bool is_amax,
	at::ScalarType dtype,
	at::OptionalIntArrayRef scale_shape) {
  PT_OP_INFO("cast_to_fp8_v2_autograd :", DUMP_6ARGS(input, scale, stochastic_rounding, is_amax, dtype, scale_shape));
  auto result = CastToFp8V2Function::apply(input, scale, stochastic_rounding, is_amax, dtype, scale_shape);
  return {result[0], result[1]};
}


::std::tuple<at::Tensor,at::Tensor> cast_to_fp8_v2_dispatch(
	const at::Tensor & input,
	const ::std::optional<at::Tensor> & scale,
	bool stochastic_rounding,
	bool is_amax,
	at::ScalarType dtype,
	at::OptionalIntArrayRef scale_shape) {
  static auto op = torch::Dispatcher::singleton()
                       .findSchemaOrThrow("hpu::cast_to_fp8_v2", "")
                       .typed<decltype(cast_to_fp8_v2_dispatch)>();

  return op.call(input, scale, stochastic_rounding, is_amax, dtype, scale_shape);
}


TORCH_LIBRARY_IMPL(hpu, AutogradHPU, m) {
  m.impl("cast_to_fp8_v2", static_cast<::std::tuple<at::Tensor,at::Tensor> (*)(const at::Tensor &, const ::std::optional<at::Tensor> &, bool, bool, at::ScalarType, at::OptionalIntArrayRef)>(&cast_to_fp8_v2_autograd));
}

}  // namespace habana

