// Autogenerated file by run_gen_op.py. Do not edit directly!
/**
 * Copyright (c) 2024-2025 Intel Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
#include "sl_report_generator/src/stack_generator.h"
#include "sl_report_generator/src/executor.h"
#include "sl_report_generator/src/shared_layer_report_generator.h"
#include "generated/slrg/registry.h"
#include "generated/slrg/validator_headers.h"
#include <c10/core/ScalarType.h>
namespace slrg {
static SchemaStackGenerator stack_generator_addbmm("Tensor self, Tensor batch1, Tensor batch2, Scalar beta, Scalar alpha", "addbmm", "addbmm");
static SchemaStackGenerator stack_generator_bucketize_Scalar("Scalar self, Tensor boundaries, bool out_int32, bool right", "bucketize", "bucketize.Scalar");
static SchemaStackGenerator stack_generator_elu("Tensor self, Scalar alpha, Scalar scale, Scalar input_scale", "elu", "elu");
static CustomSharedLayerExecutor shared_layer_executor_addbmm(&stack_generator_addbmm, &habana::validator_addbmm);
static GenericSharedLayerExecutor shared_layer_executor_bucketize_Scalar(&stack_generator_bucketize_Scalar, &habana::validator_bucketize_Scalar);
static GenericSharedLayerExecutor shared_layer_executor_elu(&stack_generator_elu, &habana::validator_elu);
void register_auto_generated_executors(slrg::ISharedLayerReportGenerator* report_generator) {
  report_generator->register_op({"addbmm", "addbmm", "torch"}, &shared_layer_executor_addbmm);
  report_generator->register_op({"addbmm", "addbmm", "torch.Tensor"}, &shared_layer_executor_addbmm);
  report_generator->register_op({"bucketize", "bucketize.Scalar", "torch"}, &shared_layer_executor_bucketize_Scalar);
  report_generator->register_op({"ELU", "elu", "torch.nn"}, &shared_layer_executor_elu);
  report_generator->register_op({"elu", "elu", "torch.nn.functional"}, &shared_layer_executor_elu);
}
}  // namespace slrg

