// Autogenerated file by run_gen_op.py. Do not edit directly!

#pragma once
#include <ATen/Tensor.h>

#include "habana_eager/ops/eager_op.h"
#include "hpu_ops/hpu_op_helper.h"

namespace habana {


at::Tensor & mul_out(const at::Tensor & self, const at::Scalar & other, at::Tensor & out);
OUTSHAPE_DECL(BinaryOutputShape);

}  // namespace habana

