// Autogenerated file by run_gen_op.py. Do not edit directly!

#pragma once
#include <ATen/Tensor.h>

#include "habana_eager/ops/eager_op.h"
#include "hpu_ops/hpu_op_helper.h"

namespace habana {


at::Tensor squeeze(const at::Tensor & self, at::IntArrayRef dim);
OUTMETA_DECL(SqueezeDimsMeta);

}  // namespace habana

