---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: ^(LICENSE.txt|.devops|scripts/tests/files/)
  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.13
    hooks:
      - id: cmake-format
        additional_dependencies: ["pyyaml"]
  #       - id: cmake-lint
  #         additional_dependencies: ["pyyaml"]
  - repo: https://github.com/aostrowski/pre-commit-mirror-git-clang-format
    rev: v10.0.1
    hooks:
      - id: git-clang-format
        exclude: ^(scripts/tests/files/|.devops/patches/)
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        name: TorchFix
        args: ["--select=TOR0,TOR102,TOR103,TOR2"]
        additional_dependencies:
          - torchfix==0.7.0
  - repo: local
    hooks:
      - id: check-bash-syntax
        name: Check shell scripts syntax
        entry: bash -n
        language: system
        files: \.(ba)?sh$
      - id: ensure-new-cpp-files-are-added-to-cmake
        name: Ensure new C++ files are added to CMake
        entry: scripts/ensure_new_cpp_files_are_added_to_cmake.sh
        language: script
        types: [c++]
        exclude: "python_packages/habana_frameworks/torch/jit/csrc/jit_fork/|\
          ^tests/user_custom_op/|\
          ^pytorch_helpers/habana_helpers/tensor_comparator/synapse/src/infra/(float16|sim_fp16).cpp$|\
          ^scripts/tests/files/|\
          ^sl_report_generator/src/executor.cpp"
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: forbid-binary
      - id: script-must-have-extension
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.6
    hooks:
      - id: ruff
        args: [--fix]
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: insert-license
        name: Handle copyright headers in scripts
        files: \.(ba|z)?sh$|CMakeLists.txt$|\.cmake$|(?<!__init__)\.py$
        args:
          - --allow-past-years
          - --use-current-year
          # yamllint disable rule:line-length
          - --comment-style
          - |-
            ###############################################################################|#|###############################################################################
          # yamllint enable rule:line-length
  # TODO: fix issues and enable when time allows:
  # https://jira.habana-labs.com/browse/SW-121816
  #       - id: insert-license
  #         name: Handle copyright headers in C++ files
  #         files: \.c(pp)?$|\.h(pp)?$
  #         args:
  # yamllint disable rule:line-length
  #             - --comment-style
  #             - |-
  #               /*******************************************************************************| *| *******************************************************************************
  #                */
  # yamllint enable rule:line-length
  #             - --fuzzy-match-generates-todo
  #             - --use-current-year
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.29.0
    hooks:
      - id: yamllint
        files: \.ya?ml$
        # TODO: fix issues and stop excluding .ci when time allows:
        # https://jira.habana-labs.com/browse/SW-121821
        exclude: ^.ci/
  - repo: local
    hooks:
      - id: deprecated-namespaces
        name: Check deprecated namespaces
        entry: c10::(optional|string_view|nullopt)|<c10/util/string_view.h>|<c10/util/Optional.h>
        language: pygrep
        files: \.c(pp)?$|\.h(pp)?$|gen_op
