// Autogenerated file by run_gen_op.py. Do not edit directly!

#include "hpu_ops/cpu_fallback.h"
#include "hpu_ops/op_validator.h"
#include "hpu_ops/op_logger.h"
#include "common/dump_args.h"
#include "habana_kernels/lazy_custom_op_declarations.h"
#include "habana_kernels/lazy_kernels.h"
#include "habana_lazy/hpu_stage_submission.h"
using habana_lazy::LazyOp;
using habana_lazy::GraphHashBuilder;

#include "cast_to_fp8_v2.h"
#include "exp_fast_math.h"
#include "mixture_of_experts.h"
#include "softmax_fp8.h"


using habana_helpers::DTypeHelper;
using synapse_helpers::graph;
using torch::jit::Stack;


namespace habana {

CheckNodeWithSharedLayerValidator validator_exp_fast_math("exp_fast_math", "exp_fast_math_fwd", {0}, {}, nullptr, {}, false, false, false, false);


at::Tensor softmax_fp8(const at::Tensor & input, int64_t dim, const std::optional<at::Tensor> & input_scale, const std::optional<at::Tensor> & output_scale, const std::optional<at::Tensor> & inv_attn_heads, const std::optional<at::Tensor> & fused_add) {
  PT_LAZY_OP_TRACE;
  PT_LAZY_TRACE;
  PT_OP_INFO("softmax_fp8: ", DUMP_6ARGS(input, dim, input_scale, output_scale, inv_attn_heads, fused_add));

  [[maybe_unused]] bool require_h2d = false;
  [[maybe_unused]] bool require_st = false;

  LazyOp<at::Tensor> hpu_op{"hpu::softmax_fp8", {input, dim, input_scale, output_scale, inv_attn_heads, fused_add}};
  hpu_op.SetOutputMetaFn(SoftmaxFp8Meta);
  RUN_MAYBE_WITH_ACC_THREAD(softmax_fp8, hpu_op);
}

at::Tensor exp_fast_math(const at::Tensor & self) {
  PT_LAZY_OP_TRACE;
  PT_LAZY_TRACE;
  PT_OP_INFO("exp_fast_math: ", DUMP_ARG(self));

  [[maybe_unused]] bool require_h2d = false;
  [[maybe_unused]] bool require_st = false;

  VAL_FAIL_CUSTOM_IF_UNSUPPORTED_DTYPE(exp_fast_math, false, self)

  LazyOp<at::Tensor> hpu_op{"hpu::exp_fast_math", {self}};
  RUN_MAYBE_WITH_ACC_THREAD(exp_fast_math, hpu_op);
}

at::Tensor mixture_of_experts(const at::Tensor & hidden_states, const at::Tensor & expert_routing_table, const at::Tensor & router_weights, at::TensorList w12, at::TensorList w3, const at::Tensor & d_scale_hidden_states, at::TensorList d_scale_intermediate_hidden_states, at::TensorList d_scale_w12, at::TensorList d_scale_w3, bool permuted_weights, std::string_view activation, int64_t experts_min, int64_t experts_max) {
  PT_LAZY_OP_TRACE;
  PT_LAZY_TRACE;
  PT_OP_INFO("mixture_of_experts: ", DUMP_13ARGS(hidden_states, expert_routing_table, router_weights, w12, w3, d_scale_hidden_states, d_scale_intermediate_hidden_states, d_scale_w12, d_scale_w3, permuted_weights, activation, experts_min, experts_max));

  [[maybe_unused]] bool require_h2d = false;
  [[maybe_unused]] bool require_st = false;

  LazyOp<at::Tensor> hpu_op{"hpu::mixture_of_experts", {hidden_states, expert_routing_table, router_weights, w12, w3, d_scale_hidden_states, d_scale_intermediate_hidden_states, d_scale_w12, d_scale_w3, permuted_weights, activation, experts_min, experts_max}};
  hpu_op.SetOutputMetaFn(MixtureOfExpertsFp8Meta);
  RUN_MAYBE_WITH_ACC_THREAD(mixture_of_experts, hpu_op);
}

::std::tuple<at::Tensor,at::Tensor> cast_to_fp8_v2(const at::Tensor & input, const std::optional<at::Tensor> & scale, bool stochastic_rounding, bool is_amax, at::ScalarType dtype, at::OptionalIntArrayRef scale_shape) {
  PT_LAZY_OP_TRACE;
  PT_LAZY_TRACE;
  PT_OP_INFO("cast_to_fp8_v2: ", DUMP_6ARGS(input, scale, stochastic_rounding, is_amax, dtype, scale_shape));

  [[maybe_unused]] bool require_h2d = false;
  [[maybe_unused]] bool require_st = false;

  LazyOp<::std::tuple<at::Tensor,at::Tensor>> hpu_op{"hpu::cast_to_fp8_v2", {input, scale, stochastic_rounding, is_amax, dtype, scale_shape}};
  hpu_op.SetOutputMetaFn(CastToFp8V2Meta);
  RUN_TUPLE_MAYBE_WITH_ACC_THREAD(cast_to_fp8_v2, hpu_op);
}





static const auto& kr_gen__custom = KernelRegistry()
;

TORCH_LIBRARY_IMPL(hpu, HPU, m) {
  m.impl("softmax_fp8", static_cast<at::Tensor (*)(const at::Tensor &, int64_t, const std::optional<at::Tensor> &, const std::optional<at::Tensor> &, const std::optional<at::Tensor> &, const std::optional<at::Tensor> &)>(&habana::softmax_fp8));
  m.impl("exp_fast_math", static_cast<at::Tensor (*)(const at::Tensor &)>(&habana::exp_fast_math));
  m.impl("mixture_of_experts.fp8_fused_weights", static_cast<at::Tensor (*)(const at::Tensor &, const at::Tensor &, const at::Tensor &, at::TensorList, at::TensorList, const at::Tensor &, at::TensorList, at::TensorList, at::TensorList, bool, std::string_view, int64_t, int64_t)>(&habana::mixture_of_experts));
  m.impl("cast_to_fp8_v2", static_cast<::std::tuple<at::Tensor,at::Tensor> (*)(const at::Tensor &, const std::optional<at::Tensor> &, bool, bool, at::ScalarType, at::OptionalIntArrayRef)>(&habana::cast_to_fp8_v2));

}



}  // namespace habana

