// Autogenerated file by run_gen_op.py. Do not edit directly!

#pragma once
#include <ATen/Tensor.h>
#include <ATen/core/function_schema.h>
#include "habana_kernels/lazy_kernels.h"
#include "hpu_ops/hpu_op_helper.h"

namespace habana {


::std::tuple<at::Tensor &,at::Tensor &> sort_out(const at::Tensor & self, std::optional<bool> stable, int64_t dim, bool descending, at::Tensor & values, at::Tensor & indices);
FALLBACK_CHECK(SortStableFallbackCheck, const at::Tensor & self, std::optional<bool> stable, int64_t dim, bool descending);

}  // namespace habana

