// Autogenerated file by run_gen_op.py. Do not edit directly!

#pragma once
#include <ATen/Tensor.h>

#include "habana_eager/ops/eager_op.h"
#include "hpu_ops/hpu_op_helper.h"

namespace habana {


::std::tuple<at::Tensor,at::Tensor,at::Tensor,at::Tensor,at::Tensor> _deform_conv2d_backward(const at::Tensor & grad, const at::Tensor & input, const at::Tensor & weight, const at::Tensor & offset, const at::Tensor & mask, const at::Tensor & bias, int64_t stride_h, int64_t stride_w, int64_t pad_h, int64_t pad_w, int64_t dilation_h, int64_t dilation_w, int64_t groups, int64_t offset_groups, bool use_mask);
OUTMETA_DECL(DeformConv2dBackwardOutputMeta);

}  // namespace habana

