// Autogenerated file by run_gen_op.py. Do not edit directly!

#pragma once
#include <ATen/Tensor.h>

#include "habana_eager/ops/eager_op.h"
#include "hpu_ops/hpu_op_helper.h"

namespace habana {


at::Tensor quantize_per_channel(const at::Tensor & input, const at::Tensor & scales, const at::Tensor & zero_points, int64_t axis, int64_t quant_min, int64_t quant_max, at::ScalarType type);
OUTMETA_DECL(QuantizePerChannelMeta);
FILL_PARAMS_DECL(FillQuantizePerChannelParams);

}  // namespace habana

