// Autogenerated file by run_gen_op.py. Do not edit directly!

#pragma once
#include <ATen/Tensor.h>
#include <ATen/core/function_schema.h>
#include "habana_kernels/lazy_kernels.h"
#include "hpu_ops/hpu_op_helper.h"

namespace habana {

HPU_OP_FRONTEND(habana_lazy::LazyOp, GeneratorToSeed)

::std::tuple<at::Tensor,at::Tensor> _fused_dropout(const at::Tensor & self, double p, ::std::optional<at::Generator> generator);
OUTMETA_DECL(FusedNativeDropoutMeta);
FILL_PARAMS_DECL(FillFusedNativeDropoutParams);

}  // namespace habana

