// Autogenerated file by run_gen_op.py. Do not edit directly!

#pragma once
#include <ATen/Tensor.h>
#include <ATen/core/function_schema.h>
#include "habana_kernels/lazy_kernels.h"
#include "hpu_ops/hpu_op_helper.h"

namespace habana {


at::Tensor bucketize(const at::Scalar & self, const at::Tensor & boundaries, bool out_int32, bool right);
OUTMETA_DECL(BucketizeMeta);
FILL_PARAMS_DECL(FillBucketizeParams);

}  // namespace habana

