// Autogenerated file by run_gen_op.py. Do not edit directly!

#pragma once
#include <ATen/Tensor.h>
#include <ATen/core/function_schema.h>
#include "habana_kernels/lazy_kernels.h"
#include "hpu_ops/hpu_op_helper.h"

namespace habana {


::std::tuple<at::Tensor,at::Tensor> cast_to_fp8_v2(const at::Tensor & input, const ::std::optional<at::Tensor> & scale, bool stochastic_rounding, bool is_amax, at::ScalarType dtype, at::OptionalIntArrayRef scale_shape);
OUTMETA_DECL(CastToFp8V2Meta);

}  // namespace habana

