// Autogenerated file by run_gen_op.py. Do not edit directly!

#pragma once
#include <ATen/ExpandUtils.h>
#include <torch/script.h>

namespace hpu_wrap {

at::Tensor matmul(const at::Tensor &, const at::Tensor &);
at::Tensor dropout(const at::Tensor &, double, bool);

} // namespace hpu_wrap

