// Autogenerated file by run_gen_op.py. Do not edit directly!

#pragma once
#include <ATen/Tensor.h>
#include <ATen/core/function_schema.h>
#include "habana_kernels/lazy_kernels.h"
#include "hpu_ops/hpu_op_helper.h"

namespace habana {


class CheckNodeWithSharedLayerValidator;
at::Tensor exp_fast_math(const at::Tensor & self);
extern CheckNodeWithSharedLayerValidator validator_exp_fast_math;

}  // namespace habana

