// Autogenerated file by run_gen_op.py. Do not edit directly!

#include "hpu_ops/op_validator.h"
#include "clone.h"
#include "prod.h"


using habana_helpers::DTypeHelper;
using synapse_helpers::graph;
using torch::jit::Stack;


namespace habana {





struct Genprod_int_out : OpBackend {
  Genprod_int_out(int device_id, c10::ScalarType scalar_type) :
      OpBackend(device_id, "reduce_prod_multi_dim_fwd", scalar_type, {}, {}, {}, true) {
  }
};

struct Genclone : OpBackend {
  Genclone(int device_id, c10::ScalarType scalar_type) :
      OpBackend(device_id, "identity", scalar_type, {0}, {}, {}, false) {
        setNoComputeFlag();
        SetOutputMetaFn(CloneMeta);
  }
};



static const auto& kr_gen_4 = KernelRegistry()
.REGISTER_HPU_BACKEND("aten::prod.int_out", Genprod_int_out)
.REGISTER_HPU_BACKEND("aten::clone", Genclone)
;




}  // namespace habana

