// Autogenerated file by run_gen_op.py. Do not edit directly!

#include "hpu_ops/op_validator.h"
#include "_deform_conv2d_backward.h"
#include "linear_backward.h"
#include "native_group_norm.h"
#include "quantize_per_channel.h"


using habana_helpers::DTypeHelper;
using synapse_helpers::graph;
using torch::jit::Stack;


namespace habana {





struct Gennative_group_norm : OpBackend {
  Gennative_group_norm(int device_id, c10::ScalarType scalar_type) :
      OpBackend(device_id, "native_group_norm_fwd", scalar_type, {0, 0, 0}, {}, {}, false) {
        SetOutputMetaFn(GroupNormFwdMeta);
        SetFillParams(FillNativeGroupNormParams);
  }
};

struct Genlinear_backward : OpBackend {
  Genlinear_backward(int device_id, c10::ScalarType scalar_type) :
      OpBackend(device_id, "linear_temp_bwd", scalar_type, {0, 0, 0}, {}, {}, false) {
        SetOutputMetaFn(LinearBackwardMeta);
        SetFillParams(FillLinearBwdParams);
  }
};

struct Genquantize_per_channel : OpBackend {
  Genquantize_per_channel(int device_id, c10::ScalarType scalar_type) :
      OpBackend(device_id, "quantize_per_channel", scalar_type, {0}, {}, {}, false) {
        SetOutputMetaFn(QuantizePerChannelMeta);
        SetFillParams(FillQuantizePerChannelParams);
  }
};

struct Gen_deform_conv2d_backward : DeformConv2dBackward {
  Gen_deform_conv2d_backward(int device_id, c10::ScalarType scalar_type) :
      DeformConv2dBackward(device_id, "None", scalar_type, {0}, {}, {}, false) {
        SetSynapseLayouts({synapse_helpers::layouts::SynapseLayoutFormat::WHCN, synapse_helpers::layouts::SynapseLayoutFormat::WHCN, synapse_helpers::layouts::SynapseLayoutFormat::SRCK, synapse_helpers::layouts::SynapseLayoutFormat::WHCN, synapse_helpers::layouts::SynapseLayoutFormat::WHCN}, {synapse_helpers::layouts::SynapseLayoutFormat::WHCN, synapse_helpers::layouts::SynapseLayoutFormat::SRCK, synapse_helpers::layouts::SynapseLayoutFormat::WHCN, synapse_helpers::layouts::SynapseLayoutFormat::WHCN, synapse_helpers::layouts::SynapseLayoutFormat::DONT_CARE});
        SetOutputMetaFn(DeformConv2dBackwardOutputMeta);
  }
};



static const auto& kr_gen_9 = KernelRegistry()
.REGISTER_HPU_BACKEND("aten::native_group_norm", Gennative_group_norm)
.REGISTER_HPU_BACKEND("aten::linear_backward", Genlinear_backward)
.REGISTER_HPU_BACKEND("quantized_decomposed::quantize_per_channel", Genquantize_per_channel)
.REGISTER_HPU_BACKEND("torchvision::_deform_conv2d_backward", Gen_deform_conv2d_backward)
;




}  // namespace habana

