// Autogenerated file by run_gen_op.py. Do not edit directly!

#include "hpu_ops/op_validator.h"
#include "eq.h"
#include "squeeze.h"


using habana_helpers::DTypeHelper;
using synapse_helpers::graph;
using torch::jit::Stack;


namespace habana {





struct Gensqueeze_dims : SqueezeDims {
  Gensqueeze_dims(int device_id, c10::ScalarType scalar_type) :
      SqueezeDims(device_id, "squeeze", scalar_type, {0}, {}, {}, false) {
        SetOutputMetaFn(SqueezeDimsMeta);
  }
};

struct Geneq_Scalar_out : OpBackend {
  Geneq_Scalar_out(int device_id, c10::ScalarType scalar_type) :
      OpBackend(device_id, "equal_fwd", scalar_type, {}, {}, {1}, true) {
        SetOutputMetaFn(CompareMeta);
        EnableTypePromotion();
        HandleBoolInputs();
  }
};



static const auto& kr_gen_6 = KernelRegistry()
.REGISTER_HPU_BACKEND("aten::squeeze.dims", Gensqueeze_dims)
.REGISTER_HPU_BACKEND("aten::eq.Scalar_out", Geneq_Scalar_out)
;




}  // namespace habana

