// Autogenerated file by run_gen_op.py. Do not edit directly!

#include "hpu_ops/op_validator.h"
#include "addbmm.h"


using habana_helpers::DTypeHelper;
using synapse_helpers::graph;
using torch::jit::Stack;


namespace habana {





struct Genaddbmm : AddBMM {
  Genaddbmm(int device_id, c10::ScalarType scalar_type) :
      AddBMM(device_id, "batch_gemm", scalar_type, {0}, {}, {}, false) {
        SetOutputMetaFn(AddBMMMeta);
        SetSharedLayerMetaFn(AddBMMSharedMeta);
  }
};



static const auto& kr_gen_2 = KernelRegistry()
.REGISTER_HPU_BACKEND("aten::addbmm", Genaddbmm)
;




}  // namespace habana

