###############################################################################
#
#  Copyright (c) 2021-2025 Intel Corporation
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
###############################################################################

"""
This module contains helper functions used in performance testing
"""

import statistics

import habana_frameworks
import torch

sep = "|"  # separator used betweeen columns
width = 88  # screen width
col_width = 10  # column width in table output
functor_op_count = 2  # number of one loop iteration in functor()


def print_header_line(header_name="", fill_symbol="-"):
    """
    prints filled line with optional message centered
    Example:
    ---- TEXT ----

    :param header_name: Optional text of line message
    :param fill_symbol: Optional symbol to fill the line
    :returns:           None
    """

    print(f"{header_name}".center(width, fill_symbol))


def print_header(header_name):
    """
    print line with column names to form a table
    Example:
    --------- Eager(sec.) ----------------------
    Op count |  Median  |   Mean   | Extra info
    --------------------------------------------

    :param header_name: Optional text of line message
    :returns:           None
    """

    print("")
    print_header_line(" " + header_name + " ")
    print("Op count".center(col_width), end="")
    print(sep, end="")
    print("Median".center(col_width), end="")
    print(sep, end="")
    print("Mean".center(col_width), end="")
    print(sep, end="")

    print(" Extra info")
    print_header_line()


def print_line(it_count, value_list):
    """
    Prints statistic of input data values to form a data line in a table
    This function logically connected with print_header() where column names
    provided for the data
    Example:
    2 |  3.71E-01|  3.82E-01|  4.28E-01|  3.71E-01|  3.71E-01

    :param it_count:   Value interpreted as counter (a first value in a row)
    :param value_list: List of numerical values used to calculate statistics
    :returns:          None
    """

    # print all values from value_list at the end of a line
    print_extra_info = 0

    print(f"{it_count:9} ", end="")
    print(sep, end="")
    print(f"{statistics.median(value_list):.2E}".rjust(col_width), end="")
    print(sep, end="")
    print(f"{statistics.mean(value_list):.2E}".rjust(col_width), end="")

    if print_extra_info:
        for it in value_list:
            print(sep, end="")
            print(f"{it:.2E}".rjust(col_width), end="")
    print("")


def create_tensor_2D_list(size_x, size_y, count):
    """
    Creates data array with randomized values using torch API
    Creates 2D tensors with diffrent shapes

    :param size_x: Size of first dimention in 2D shape
    :param size_y: Size of second dimention in 2D shape
    :param count:  Number of torch.tensor in a list
    :returns:      List of torch.tensor
    """

    tensor_list = []

    for it in range(count):
        tns = torch.randn(size_x + it, size_y + it).to("hpu")
        tensor_list.append(tns)

    return tensor_list


def create_functor(operations_count):
    """
    Return a function with set of data dependant functions to
    form graph-like execution.
    Used to simulate large network execution flow.

    :param operations_count: Number of operations in the set
    :returns:                Pointer to function
    """

    # use simple python defined function with a loop
    # or auto generated set with real function calls instead loop (unrolled)
    use_python_function = 1

    if use_python_function:

        def functor(arg1, arg2):
            """
            Simulate large network execution flow

            :param arg1: Torch.Tensor with data
            :param arg2: Torch.Tensor with data
            :returns:    Torch.Tensor with sequence output result
            """

            result = arg1
            for _ in range(operations_count):
                result_mul = torch.mul(result, arg2)
                result = torch.add(result_mul, arg2)

            return result

        return functor
    else:
        fs = "def functor_gen(arg1, arg2):\n"
        fs += '    """autogenerated function to simulate network"""\n'
        fs += "    result = arg1\n"

        for _ in range(operations_count):
            fs += "    result_mul = torch.mul(result, arg2)\n"
            fs += "    result = torch.add(result_mul, arg2)\n"

        fs += "    return result\n"
        # print(fs)

        fs_compiled = compile(fs, "auto_generated", "exec")
        exec(fs_compiled)
        functor_generated = eval("functor_gen")

        return functor_generated


def print_dev_stat():
    """
    Print some statistic about Gaudi device

    :param :
    :returns:
    """

    print_header_line("Gaudi device")

    print(f"lazy mode: {habana_frameworks.torch.utils.internal.is_lazy()}")
    print("hpu available:", habana_frameworks.torch.hpu.is_available())
    print("hpu device count:", habana_frameworks.torch.hpu.device_count())
    print("hpu device name:", habana_frameworks.torch.hpu.get_device_name())
    print("hpu current device:", habana_frameworks.torch.hpu.current_device())
    print("hpu synchronize:", habana_frameworks.torch.hpu.synchronize())
    print("hpu memory_usage:", habana_frameworks.torch.hpu.memory_usage())

    cap = habana_frameworks.torch.hpu.get_device_capability("hpu")
    print("hpu get_device_capability:", cap)

    print_header_line()
