###############################################################################
#
#  Copyright (c) 2021-2025 Intel Corporation
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
###############################################################################


H_HEADER = """// Autogenerated file by {gen}. Do not edit directly!

#pragma once
#include <ATen/Tensor.h>
#include <ATen/core/function_schema.h>
#include "habana_kernels/lazy_kernels.h"
#include "hpu_ops/hpu_op_helper.h"

namespace habana {{
{op_backend_classes}
{op_frontend_classes}
{header_decls}
}}  // namespace habana
"""


H_HEADER_EAGER = """// Autogenerated file by {gen}. Do not edit directly!

#pragma once
#include <ATen/Tensor.h>

#include "habana_eager/ops/eager_op.h"
#include "hpu_ops/hpu_op_helper.h"

namespace habana {{
{op_backend_classes}
{op_frontend_classes}
{header_decls}
}}  // namespace habana
"""

CPP_HEADER = """// Autogenerated file by {gen}. Do not edit directly!
{header_inclusions}

using habana_helpers::DTypeHelper;
using synapse_helpers::graph;
using torch::jit::Stack;


namespace habana {{

{dtype_defs}

{funcs}

{op_backend}

static const auto& kr_gen_{file_idx} = KernelRegistry()
{kr_regs};

{torch_regs}

{custom_schema_regs}
}}  // namespace habana
"""


CPP_HEADER_CHECK_KERNEL_SUPPORT = """// Autogenerated file by {gen}. Do not edit directly!
{header_inclusions}

namespace habana {{

{dtype_defs}

{funcs}

{op_backend}

}}  // namespace habana
"""


OPCLASS_HEADER = """struct {cname} : {op_backend_class} {{
  {cname}(int device_id, c10::ScalarType scalar_type) :
      {op_backend_class}(device_id, \"{guid}\", scalar_type, {{{out_ids}}}, {{{inplace_ids}}}, {{{scalar_ids}}}, {is_out_fn}) {{{ctor_extra_calls}
  }}{custom_handler}
}};
"""

CUSTOM_HANDLER = """

  void CustomHandler(graph &g, Stack& stack) override {{
    static_cast<void>(g);
    static_cast<void>(stack);
    {body}
  }}"""


AUTOCAST_TEMPLATE = """// Autogenerated file by {gen}. Do not edit directly!
/**
* Copyright (c) 2021-2024 Intel Corporation
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

#include <ATen/ATen.h>
#include <ATen/NativeFunctions.h>
#include <torch/library.h>
#include "hpu_ops/autocast_helpers.h"

namespace at {{
namespace autocast {{
namespace {{

using tuple_2_tensors = std::tuple<Tensor, Tensor>;
using tuple_3_tensors = std::tuple<Tensor, Tensor, Tensor>;
using tuple_4_tensors = std::tuple<Tensor, Tensor, Tensor, Tensor>;
using tuple_5_tensors = std::tuple<Tensor, Tensor, Tensor, Tensor, Tensor>;
using tuple_6_tensors = std::tuple<Tensor, Tensor, Tensor, Tensor, Tensor, Tensor>;
using tuple_4_tensors_int64 = std::tuple<Tensor,Tensor,Tensor,Tensor,int64_t>;
using tuple_2_tensors_double_int64 = std::tuple<Tensor,Tensor,double,int64_t>;
using tuple_3_tensors_vector = std::tuple<Tensor,Tensor,Tensor,::std::vector<Tensor>>;
using tuple_double_int64 = std::tuple<double,int64_t>;
using tuple_tensor_vector = std::tuple<Tensor,::std::vector<Tensor>>;
using tuple_vector_tensor = std::tuple<::std::vector<Tensor>,Tensor>;
using tuple_tensor_2_vectors = std::tuple<Tensor,::std::vector<Tensor>,::std::vector<Tensor>>;
using tuple_4_tensors_2_int64_2_tensors = std::tuple<at::Tensor,at::Tensor,at::Tensor,at::Tensor,int64_t,int64_t,at::Tensor,at::Tensor>;
using tuple_4_tensors_4_int64_tensor = std::tuple<Tensor,Tensor,Tensor,Tensor,int64_t,int64_t,int64_t,int64_t,Tensor>;
using tuple_2_tensors_2_int64_tensor = std::tuple<Tensor,Tensor,int64_t,int64_t,Tensor>;
using tuple_4_tensors_2_int64_3_tensor = std::tuple<Tensor,Tensor,Tensor,Tensor,int64_t,int64_t,Tensor,Tensor,Tensor>;
using tuple_4_tensors_2_int64 = std::tuple<Tensor,Tensor,Tensor,Tensor,int64_t,int64_t>;
using tuple_3_vectors = std::tuple<::std::vector<at::Tensor>,::std::vector<at::Tensor>,::std::vector<at::Tensor>>;
using tuple_5_vectors = std::tuple<::std::vector<at::Tensor>,::std::vector<at::Tensor>,::std::vector<at::Tensor>,::std::vector<at::Tensor>,::std::vector<at::Tensor>>;
using tuple_4_vectors = std::tuple<::std::vector<at::Tensor>,::std::vector<at::Tensor>,::std::vector<at::Tensor>,::std::vector<at::Tensor>>;
{fallback_fallthrough}
TORCH_LIBRARY_IMPL(aten, AutocastHPU, m) {{
{ops_registrations}
}}

}} // namespace
}} // namespace autocast
}} // namespace at
"""

AUTOCAST_FALLBACK = """
TORCH_LIBRARY_IMPL(_, AutocastHPU, m) {{
  m.fallback(torch::CppFunction::makeFallthrough());
}}
"""

HPU_WRAP_REGS = """// Autogenerated file by {gen}. Do not edit directly!
#include "wrap_kernels_declarations.h"

namespace habana {{
{regs}
}}  // namespace habana
"""

HPU_WRAP_HEADERS = """// Autogenerated file by {gen}. Do not edit directly!

#pragma once
#include <ATen/ExpandUtils.h>
#include <torch/script.h>

namespace hpu_wrap {{

{headers}

}} // namespace hpu_wrap
"""

STACK_POP_CODE_FORMAT_ = """
      {}

      {}

      auto is_supported = impl({}, is_dynamic);
      return is_supported;
    }}
"""

TORCHGEN_POP_CODE_FORMAT_ = """
    {}
      auto is_supported = impl({}, is_dynamic);
      return is_supported;
    }}
"""

AUTOGRAD_H_FILE = """// Autogenerated file by {gen}. Do not edit directly!

#pragma once
#include <torch/library.h>
#include <c10/core/ScalarType.h>
#include <torch/csrc/autograd/custom_function.h>

using namespace at;

namespace habana {{

{autograd_functions}
{dispatch_functions}
}} // namespace habana
"""

AUTOGRAD_CLASS_DEFINITION = """
class {autograd_class_name}
    : public torch::autograd::Function<{autograd_class_name}> {{
 public:
  static {return_type} forward(
      torch::autograd::AutogradContext* ctx,
      {input_params});
  static std::vector<at::Tensor> backward(
      torch::autograd::AutogradContext* ctx,
      const std::vector<at::Tensor>& grads);
}};
"""

AUTOGRAD_DISPATCH_FUNCTION = """{return_type} {dispatch_op_name}(\n\t{inputs}) {{
  static auto op = torch::Dispatcher::singleton()
                       .findSchemaOrThrow("hpu::{op_name}", "{variant_name}")
                       .typed<decltype({dispatch_op_name})>();

  return op.call({input_names});
}}

"""

AUTOGRAD_CPP_FILE = """// Autogenerated file by {gen}. Do not edit directly!

#include "hpu_ops/op_logger.h"
#include "habana_helpers/logging.h"
#include "common/dump_args.h"
#include <torch/torch.h>
#include "autograd_ops.h"

namespace habana {{

using namespace at;

{frontend}
{dispatch_functions}
{impls}
}}  // namespace habana
"""

CHECK_KERNEL_SUPPORT_HEADERS = """
#include <torch/extension.h>
#include <pybind11/stl.h>
#include <pybind11/pybind11.h>
#include <torch/csrc/jit/tensorexpr/tensorexpr_init.h>
#include <torch/csrc/jit/python/pybind_utils.h>
#include "cpu_fallback.h"

using habana_helpers::DTypeHelper;
using namespace torch::jit;
"""

OPTIONAL_STRING = """std::vector<int64_t> {name}_opt_in_vec;
auto {name}_opt = {name}.toOptional<c10::IValue>();
at::OptionalIntArrayRef {name}_opt_out;
if ({name}_opt.has_value()) {{
  const c10::IValue {name}_opt_in = {name}_opt.value();
  const c10::List<c10::IValue> {name}_opt_in_list_in = {name}_opt_in.toList();
  for (c10::IValue {name}_opt_in_elem : {name}_opt_in_list_in) {{
    int64_t {name}_opt_in_elem_base = {name}_opt_in_elem.to<int64_t>();
    {name}_opt_in_vec.push_back({name}_opt_in_elem_base);
  }}
  at::IntArrayRef {name}_opt_in_list_out({name}_opt_in_vec);
  {name}_opt_out = at::OptionalIntArrayRef({name}_opt_in_list_out);
}} else {{
  {name}_opt_out = at::OptionalIntArrayRef();
}}
"""

AUTO_COMPUTE_TYPE = """  auto compute_type = DTypeHelper::get_compute_dtype({{{dtype_helper_inputs}}}, {fe_call_args}, DTypeHelper::DtypePromoteVariant::k{type_promo_variant}, {safe_cast}/*safe_cast*/{param_vars});
  static_cast<void>(compute_type);

"""

_SLRG_VALIDATOR_HEADERS = """// Autogenerated file by {gen}. Do not edit directly!
/**
 * Copyright (c) 2024-2025 Intel Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
#pragma once
{headers}
"""

_SLRG_REGISTRY_CPP = """// Autogenerated file by {gen}. Do not edit directly!
/**
 * Copyright (c) 2024-2025 Intel Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
#include "sl_report_generator/src/stack_generator.h"
#include "sl_report_generator/src/executor.h"
#include "sl_report_generator/src/shared_layer_report_generator.h"
#include "generated/slrg/registry.h"
#include "generated/slrg/validator_headers.h"
#include <c10/core/ScalarType.h>
namespace slrg {{
{generators}
{executors}
void register_auto_generated_executors(slrg::ISharedLayerReportGenerator* report_generator) {{
{funcs}
}}
}}  // namespace slrg
"""

_SLRG_REGISTRY_H = """// Autogenerated file by {gen}. Do not edit directly!
/**
 * Copyright (c) 2024-2025 Intel Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
#pragma once
namespace slrg {{
class ISharedLayerReportGenerator;
void register_auto_generated_executors(ISharedLayerReportGenerator* report_generator);
}}  // namespace slrg
"""
