###############################################################################
#
#  Copyright (c) 2021-2025 Intel Corporation
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
###############################################################################

##############################################################################
# Copyright (C) 2023 Habana Labs, Ltd. an Intel Company
# All Rights Reserved.
#
# Unauthorized copying of this file or any element(s) within it, via any medium
# is strictly prohibited.
# This file contains Habana Labs, Ltd. proprietary and confidential information
# and is subject to the confidentiality and license agreements under which it
# was provided.
#
###############################################################################
from test_infra_hpu import pytorch_version

pt_dir = pytorch_version + "/pytorch"

# Below are tests across all categories that are failing on CPU also
cpu_failed_tests_to_skip = {
    "https://jira.habana-labs.com/browse/MCW-1622": [
        # CPU xfails from files: test_ops.py, test_decomp.py,
        # test_ops_gradients.py and test_reductions.py
        # _pytest.outcomes.XFailed
        pt_dir + "/test/test_ops_gradients.py::TestGradientsHPU::test_fn_fwgrad_bwgrad_bfloat16_hpu_complex128",
        pt_dir + "/test/test_ops_gradients.py::TestGradientsHPU::test_fn_fwgrad_bwgrad_bfloat16_hpu_float64",
        pt_dir + "/test/test_ops_gradients.py::TestGradientsHPU::test_fn_fwgrad_bwgrad_chalf_hpu_complex128",
        pt_dir + "/test/test_ops_gradients.py::TestGradientsHPU::test_fn_fwgrad_bwgrad_chalf_hpu_float64",
        pt_dir + "/test/test_ops_gradients.py::TestGradientsHPU::test_fn_fwgrad_bwgrad_float_hpu_complex128",
        pt_dir + "/test/test_ops_gradients.py::TestGradientsHPU::test_fn_fwgrad_bwgrad_float_hpu_float64",
        pt_dir + "/test/test_ops_gradients.py::TestGradientsHPU::test_fn_fwgrad_bwgrad_half_hpu_complex128",
        pt_dir + "/test/test_ops_gradients.py::TestGradientsHPU::test_fn_fwgrad_bwgrad_half_hpu_float64",
        pt_dir
        + "/test/test_ops_gradients.py::TestGradientsHPU::test_fn_fwgrad_bwgrad_linalg_det_singular_hpu_complex128",
        pt_dir
        + "/test/test_ops_gradients.py::TestGradientsHPU::test_fn_fwgrad_bwgrad_linalg_norm_subgradients_at_zero_hpu_complex128",
        pt_dir
        + "/test/test_ops_gradients.py::TestGradientsHPU::test_fn_fwgrad_bwgrad_linalg_norm_subgradients_at_zero_hpu_float64",
        pt_dir + "/test/test_ops_gradients.py::TestGradientsHPU::test_fn_fwgrad_bwgrad_polar_hpu_float64",
        pt_dir + "/test/test_ops_gradients.py::TestGradientsHPU::test_fn_fwgrad_bwgrad_scatter_reduce_prod_hpu_float64",
        pt_dir + "/test/test_ops_gradients.py::TestGradientsHPU::test_fn_fwgrad_bwgrad_triangular_solve_hpu_complex128",
        pt_dir + "/test/test_ops_gradients.py::TestGradientsHPU::test_fn_fwgrad_bwgrad_triangular_solve_hpu_float64",
        pt_dir + "/test/test_ops_gradients.py::TestGradientsHPU::test_fn_grad_as_strided_scatter_hpu_complex128",
        pt_dir + "/test/test_ops_gradients.py::TestGradientsHPU::test_fn_grad_as_strided_scatter_hpu_float64",
        pt_dir + "/test/test_ops_gradients.py::TestGradientsHPU::test_fn_grad_bfloat16_hpu_complex128",
        pt_dir + "/test/test_ops_gradients.py::TestGradientsHPU::test_fn_grad_bfloat16_hpu_float64",
        pt_dir + "/test/test_ops_gradients.py::TestGradientsHPU::test_fn_grad_chalf_hpu_complex128",
        pt_dir + "/test/test_ops_gradients.py::TestGradientsHPU::test_fn_grad_chalf_hpu_float64",
        pt_dir + "/test/test_ops_gradients.py::TestGradientsHPU::test_fn_grad_cov_hpu_complex128",
        pt_dir + "/test/test_ops_gradients.py::TestGradientsHPU::test_fn_grad_cov_hpu_float64",
        pt_dir + "/test/test_ops_gradients.py::TestGradientsHPU::test_fn_grad_float_hpu_complex128",
        pt_dir + "/test/test_ops_gradients.py::TestGradientsHPU::test_fn_grad_float_hpu_float64",
        pt_dir + "/test/test_ops_gradients.py::TestGradientsHPU::test_fn_grad_half_hpu_complex128",
        pt_dir + "/test/test_ops_gradients.py::TestGradientsHPU::test_fn_grad_half_hpu_float64",
        pt_dir + "/test/test_ops_gradients.py::TestGradientsHPU::test_fn_grad_istft_hpu_complex128",
        pt_dir + "/test/test_ops_gradients.py::TestGradientsHPU::test_fn_grad_istft_hpu_float64",
        pt_dir
        + "/test/test_ops_gradients.py::TestGradientsHPU::test_fn_grad_linalg_norm_subgradients_at_zero_hpu_complex128",
        pt_dir + "/test/test_ops_gradients.py::TestGradientsHPU::test_fn_grad_nn_functional_ctc_loss_hpu_float64",
        pt_dir + "/test/test_ops_gradients.py::TestGradientsHPU::test_fn_gradgrad_as_strided_scatter_hpu_complex128",
        pt_dir + "/test/test_ops_gradients.py::TestGradientsHPU::test_fn_gradgrad_as_strided_scatter_hpu_float64",
        pt_dir + "/test/test_ops_gradients.py::TestGradientsHPU::test_fn_gradgrad_bfloat16_hpu_complex128",
        pt_dir + "/test/test_ops_gradients.py::TestGradientsHPU::test_fn_gradgrad_bfloat16_hpu_float64",
        pt_dir + "/test/test_ops_gradients.py::TestGradientsHPU::test_fn_gradgrad_chalf_hpu_complex128",
        pt_dir + "/test/test_ops_gradients.py::TestGradientsHPU::test_fn_gradgrad_chalf_hpu_float64",
        pt_dir + "/test/test_ops_gradients.py::TestGradientsHPU::test_fn_gradgrad_cov_hpu_complex128",
        pt_dir + "/test/test_ops_gradients.py::TestGradientsHPU::test_fn_gradgrad_cov_hpu_float64",
        pt_dir + "/test/test_ops_gradients.py::TestGradientsHPU::test_fn_gradgrad_float_hpu_complex128",
        pt_dir + "/test/test_ops_gradients.py::TestGradientsHPU::test_fn_gradgrad_float_hpu_float64",
        pt_dir + "/test/test_ops_gradients.py::TestGradientsHPU::test_fn_gradgrad_half_hpu_complex128",
        pt_dir + "/test/test_ops_gradients.py::TestGradientsHPU::test_fn_gradgrad_half_hpu_float64",
        pt_dir + "/test/test_ops_gradients.py::TestGradientsHPU::test_fn_gradgrad_linalg_det_singular_hpu_complex128",
        pt_dir + "/test/test_ops_gradients.py::TestGradientsHPU::test_fn_gradgrad_linalg_norm_hpu_complex128",
        pt_dir
        + "/test/test_ops_gradients.py::TestGradientsHPU::test_fn_gradgrad_linalg_norm_subgradients_at_zero_hpu_complex128",
        pt_dir
        + "/test/test_ops_gradients.py::TestGradientsHPU::test_fn_gradgrad_linalg_norm_subgradients_at_zero_hpu_float64",
        pt_dir + "/test/test_ops_gradients.py::TestGradientsHPU::test_fn_gradgrad_native_layer_norm_hpu_float64",
        pt_dir + "/test/test_ops_gradients.py::TestGradientsHPU::test_fn_gradgrad_nn_functional_ctc_loss_hpu_float64",
        pt_dir + "/test/test_ops_gradients.py::TestGradientsHPU::test_fn_gradgrad_nn_functional_prelu_hpu_float64",
        pt_dir + "/test/test_ops_gradients.py::TestGradientsHPU::test_forward_mode_AD_bernoulli_hpu_float64",
        pt_dir + "/test/test_ops_gradients.py::TestGradientsHPU::test_forward_mode_AD_bfloat16_hpu_complex128",
        pt_dir + "/test/test_ops_gradients.py::TestGradientsHPU::test_forward_mode_AD_bfloat16_hpu_float64",
        pt_dir + "/test/test_ops_gradients.py::TestGradientsHPU::test_forward_mode_AD_chalf_hpu_complex128",
        pt_dir + "/test/test_ops_gradients.py::TestGradientsHPU::test_forward_mode_AD_chalf_hpu_float64",
        pt_dir + "/test/test_ops_gradients.py::TestGradientsHPU::test_forward_mode_AD_cov_hpu_complex128",
        pt_dir + "/test/test_ops_gradients.py::TestGradientsHPU::test_forward_mode_AD_cov_hpu_float64",
        pt_dir + "/test/test_ops_gradients.py::TestGradientsHPU::test_forward_mode_AD_float_hpu_complex128",
        pt_dir + "/test/test_ops_gradients.py::TestGradientsHPU::test_forward_mode_AD_float_hpu_float64",
        pt_dir + "/test/test_ops_gradients.py::TestGradientsHPU::test_forward_mode_AD_half_hpu_complex128",
        pt_dir + "/test/test_ops_gradients.py::TestGradientsHPU::test_forward_mode_AD_half_hpu_float64",
        pt_dir
        + "/test/test_ops_gradients.py::TestGradientsHPU::test_forward_mode_AD_linalg_norm_subgradients_at_zero_hpu_complex128",
        pt_dir + "/test/test_ops_gradients.py::TestGradientsHPU::test_forward_mode_AD_native_batch_norm_hpu_float64",
        pt_dir
        + "/test/test_ops_gradients.py::TestGradientsHPU::test_forward_mode_AD_nn_functional_feature_alpha_dropout_with_train_hpu_float64",
        pt_dir
        + "/test/test_ops_gradients.py::TestGradientsHPU::test_forward_mode_AD_nn_functional_max_unpool3d_hpu_float64",
        pt_dir
        + "/test/test_ops_gradients.py::TestGradientsHPU::test_inplace_forward_mode_AD_nn_functional_feature_alpha_dropout_with_train_hpu_float64",
        pt_dir
        + "/test/test_ops_gradients.py::TestGradientsHPU::test_inplace_forward_mode_AD_nn_functional_rrelu_hpu_float64",
        pt_dir
        + "/test/test_ops_gradients.py::TestGradientsHPU::test_inplace_gradgrad_nn_functional_hardsigmoid_hpu_float64",
        pt_dir + "/test/test_reductions.py::TestReductionsHPU::test_dim_default_keepdim_all_hpu",
        pt_dir + "/test/test_reductions.py::TestReductionsHPU::test_dim_default_keepdim_any_hpu",
        pt_dir + "/test/test_reductions.py::TestReductionsHPU::test_dim_empty_amax_hpu",
        pt_dir + "/test/test_reductions.py::TestReductionsHPU::test_dim_empty_amin_hpu",
        pt_dir + "/test/test_reductions.py::TestReductionsHPU::test_dim_empty_keepdim_amax_hpu",
        pt_dir + "/test/test_reductions.py::TestReductionsHPU::test_dim_empty_keepdim_amin_hpu",
        pt_dir + "/test/test_reductions.py::TestReductionsHPU::test_dim_empty_keepdim_linalg_vector_norm_hpu",
        pt_dir + "/test/test_reductions.py::TestReductionsHPU::test_dim_empty_keepdim_masked_amax_hpu",
        pt_dir + "/test/test_reductions.py::TestReductionsHPU::test_dim_empty_keepdim_masked_amin_hpu",
        pt_dir + "/test/test_reductions.py::TestReductionsHPU::test_dim_empty_keepdim_masked_mean_hpu",
        pt_dir + "/test/test_reductions.py::TestReductionsHPU::test_dim_empty_keepdim_masked_norm_hpu",
        pt_dir + "/test/test_reductions.py::TestReductionsHPU::test_dim_empty_keepdim_masked_std_hpu",
        pt_dir + "/test/test_reductions.py::TestReductionsHPU::test_dim_empty_keepdim_masked_sum_hpu",
        pt_dir + "/test/test_reductions.py::TestReductionsHPU::test_dim_empty_keepdim_masked_var_hpu",
        pt_dir + "/test/test_reductions.py::TestReductionsHPU::test_dim_empty_keepdim_nansum_hpu",
        pt_dir + "/test/test_reductions.py::TestReductionsHPU::test_dim_empty_linalg_vector_norm_hpu",
        pt_dir + "/test/test_reductions.py::TestReductionsHPU::test_dim_empty_masked_amax_hpu",
        pt_dir + "/test/test_reductions.py::TestReductionsHPU::test_dim_empty_masked_amin_hpu",
        pt_dir + "/test/test_reductions.py::TestReductionsHPU::test_dim_empty_masked_mean_hpu",
        pt_dir + "/test/test_reductions.py::TestReductionsHPU::test_dim_empty_masked_norm_hpu",
        pt_dir + "/test/test_reductions.py::TestReductionsHPU::test_dim_empty_masked_std_hpu",
        pt_dir + "/test/test_reductions.py::TestReductionsHPU::test_dim_empty_masked_sum_hpu",
        pt_dir + "/test/test_reductions.py::TestReductionsHPU::test_dim_empty_masked_var_hpu",
        pt_dir + "/test/test_reductions.py::TestReductionsHPU::test_dim_empty_nansum_hpu",
        pt_dir + "/test/test_reductions.py::TestReductionsHPU::test_dim_none_all_hpu",
        pt_dir + "/test/test_reductions.py::TestReductionsHPU::test_dim_none_any_hpu",
        pt_dir + "/test/test_reductions.py::TestReductionsHPU::test_dim_none_keepdim_all_hpu",
        pt_dir + "/test/test_reductions.py::TestReductionsHPU::test_dim_none_keepdim_any_hpu",
        pt_dir + "/test/test_reductions.py::TestReductionsHPU::test_ref_duplicate_values_masked_mean_hpu_bool",
        pt_dir + "/test/test_reductions.py::TestReductionsHPU::test_ref_small_input_masked_mean_hpu_bool",
        pt_dir + "/test/test_reductions.py::TestReductionsHPU::test_reference_masked_masked_argmax_hpu_bfloat16",
        pt_dir + "/test/test_reductions.py::TestReductionsHPU::test_reference_masked_masked_argmax_hpu_float32",
        pt_dir + "/test/test_reductions.py::TestReductionsHPU::test_reference_masked_masked_argmax_hpu_float64",
        pt_dir + "/test/test_reductions.py::TestReductionsHPU::test_reference_masked_masked_argmax_hpu_int16",
        pt_dir + "/test/test_reductions.py::TestReductionsHPU::test_reference_masked_masked_argmax_hpu_int32",
        pt_dir + "/test/test_reductions.py::TestReductionsHPU::test_reference_masked_masked_argmax_hpu_int64",
        pt_dir + "/test/test_reductions.py::TestReductionsHPU::test_reference_masked_masked_argmax_hpu_int8",
        pt_dir + "/test/test_reductions.py::TestReductionsHPU::test_reference_masked_masked_argmax_hpu_uint8",
        pt_dir + "/test/test_reductions.py::TestReductionsHPU::test_reference_masked_masked_argmin_hpu_bfloat16",
        pt_dir + "/test/test_reductions.py::TestReductionsHPU::test_reference_masked_masked_argmin_hpu_float32",
        pt_dir + "/test/test_reductions.py::TestReductionsHPU::test_reference_masked_masked_argmin_hpu_float64",
        pt_dir + "/test/test_reductions.py::TestReductionsHPU::test_reference_masked_masked_argmin_hpu_int16",
        pt_dir + "/test/test_reductions.py::TestReductionsHPU::test_reference_masked_masked_argmin_hpu_int32",
        pt_dir + "/test/test_reductions.py::TestReductionsHPU::test_reference_masked_masked_argmin_hpu_int64",
        pt_dir + "/test/test_reductions.py::TestReductionsHPU::test_reference_masked_masked_argmin_hpu_int8",
        pt_dir + "/test/test_reductions.py::TestReductionsHPU::test_reference_masked_masked_argmin_hpu_uint8",
        pt_dir + "/test/test_reductions.py::TestReductionsHPU::test_reference_masked_masked_mean_hpu_bool",
        pt_dir + "/test/test_reductions.py::TestReductionsHPU::test_result_dtype_all_hpu_uint8",
        pt_dir + "/test/test_reductions.py::TestReductionsHPU::test_result_dtype_any_hpu_uint8",
        pt_dir + "/test/test_decomp.py::TestDecompHPU::test_comprehensive_pca_lowrank_hpu_float32",
        pt_dir + "/test/test_decomp.py::TestDecompHPU::test_comprehensive_pca_lowrank_hpu_float64",
        pt_dir + "/test/test_decomp.py::TestDecompHPU::test_comprehensive_randn_hpu_bfloat16",
        pt_dir + "/test/test_decomp.py::TestDecompHPU::test_comprehensive_randn_hpu_float32",
        pt_dir + "/test/test_decomp.py::TestDecompHPU::test_comprehensive_randn_hpu_float64",
        pt_dir + "/test/test_decomp.py::TestDecompHPU::test_comprehensive_svd_lowrank_hpu_float32",
        pt_dir + "/test/test_decomp.py::TestDecompHPU::test_comprehensive_svd_lowrank_hpu_float64",
        pt_dir + "/test/test_decomp.py::TestDecompHPU::test_comprehensive_randn_hpu_complex128",
        pt_dir + "/test/test_decomp.py::TestDecompHPU::test_comprehensive_randn_hpu_complex32",
        pt_dir + "/test/test_decomp.py::TestDecompHPU::test_comprehensive_randn_hpu_complex64",
        pt_dir + "/test/test_decomp.py::TestDecompHPU::test_comprehensive_randn_hpu_float16",
        pt_dir + "/test/test_decomp.py::TestDecompHPU::test_quick_randn_hpu_bfloat16",
        pt_dir + "/test/test_decomp.py::TestDecompHPU::test_quick_randn_hpu_float32",
        pt_dir + "/test/test_decomp.py::TestDecompHPU::test_quick_randn_hpu_float64",
        pt_dir + "/test/test_decomp.py::TestDecompHPU::test_quick_uniform_hpu_bfloat16",
        pt_dir + "/test/test_decomp.py::TestDecompHPU::test_quick_uniform_hpu_float32",
        pt_dir + "/test/test_decomp.py::TestDecompHPU::test_quick_uniform_hpu_float64",
        pt_dir + "/test/test_decomp.py::TestDecompHPU::test_quick_randn_hpu_complex128",
        pt_dir + "/test/test_decomp.py::TestDecompHPU::test_quick_randn_hpu_complex32",
        pt_dir + "/test/test_decomp.py::TestDecompHPU::test_quick_randn_hpu_complex64",
        pt_dir + "/test/test_decomp.py::TestDecompHPU::test_quick_randn_hpu_float16",
        pt_dir + "/test/test_decomp.py::TestDecompHPU::test_quick_uniform_hpu_complex128",
        pt_dir + "/test/test_decomp.py::TestDecompHPU::test_quick_uniform_hpu_complex64",
        pt_dir + "/test/test_decomp.py::TestDecompHPU::test_quick_uniform_hpu_float16",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_dtypes_geqrf_hpu",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_dtypes_ormqr_hpu",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_dtypes_resize__hpu",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_dtypes_resize_as__hpu",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_errors_clamp_max_hpu",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_errors_clamp_min_hpu",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_noncontiguous_samples_arange_hpu_float32",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_noncontiguous_samples_arange_hpu_int64",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_noncontiguous_samples_as_strided_hpu_complex64",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_noncontiguous_samples_as_strided_hpu_float32",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_noncontiguous_samples_as_strided_hpu_int64",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_noncontiguous_samples_linspace_hpu_complex64",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_noncontiguous_samples_linspace_hpu_float32",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_noncontiguous_samples_linspace_hpu_int64",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_noncontiguous_samples_logspace_hpu_complex64",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_noncontiguous_samples_logspace_hpu_float32",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_noncontiguous_samples_logspace_hpu_int64",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_noncontiguous_samples_ones_hpu_complex64",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_noncontiguous_samples_ones_hpu_float32",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_noncontiguous_samples_ones_hpu_int64",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_noncontiguous_samples_view_as_complex_hpu_float32",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_noncontiguous_samples_zeros_hpu_complex64",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_noncontiguous_samples_zeros_hpu_float32",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_noncontiguous_samples_zeros_hpu_int64",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_numpy_ref_clone_hpu_complex128",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_numpy_ref_clone_hpu_float64",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_numpy_ref_clone_hpu_int64",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_numpy_ref_nn_functional_conv_transpose1d_hpu_int64",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_out_aminmax_hpu_float32",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_out_bernoulli_hpu_float32",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_out_cholesky_inverse_hpu_float32",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_out_cumprod_hpu_float32",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_out_cumsum_hpu_float32",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_out_fft_ihfft2_hpu_float32",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_out_fft_ihfftn_hpu_float32",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_out_geqrf_hpu_float32",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_out_linalg_eig_hpu_float32",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_out_lu_hpu_float32",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_out_matmul_hpu_float32",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_out_narrow_copy_hpu_float32",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_out_native_batch_norm_hpu_float32",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_out_nn_functional_avg_pool3d_hpu_float32",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_out_nn_functional_linear_hpu_float32",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_out_nonzero_hpu_float32",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_out_norm_fro_hpu_float32",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_out_norm_nuc_hpu_float32",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_out_normal_hpu_float32",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_out_ormqr_hpu_float32",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_out_randn_hpu_float32",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_out_triangular_solve_hpu_float32",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_out_warning_addbmm_hpu",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_out_warning_arange_hpu",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_out_warning_bernoulli_hpu",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_out_warning_eye_hpu",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_out_warning_fft_ihfft2_hpu",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_out_warning_fft_ihfftn_hpu",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_out_warning_linspace_hpu",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_out_warning_logspace_hpu",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_out_warning_lu_hpu",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_out_warning_mode_hpu",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_out_warning_multinomial_hpu",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_out_warning_narrow_copy_hpu",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_out_warning_native_batch_norm_hpu",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_out_warning_nn_functional_logsigmoid_hpu",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_out_warning_nonzero_hpu",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_out_warning_normal_hpu",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_out_warning_ones_hpu",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_out_warning_randn_hpu",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_out_warning_zeros_hpu",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref__refs_abs_hpu_complex32",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref__refs_addr_hpu_bfloat16",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref__refs_addr_hpu_bool",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref__refs_addr_hpu_complex128",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref__refs_addr_hpu_complex64",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref__refs_addr_hpu_float16",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref__refs_addr_hpu_float32",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref__refs_addr_hpu_float64",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref__refs_addr_hpu_int16",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref__refs_addr_hpu_int32",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref__refs_addr_hpu_int64",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref__refs_addr_hpu_int8",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref__refs_addr_hpu_uint8",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref__refs_index_add_hpu_bfloat16",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref__refs_index_add_hpu_bool",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref__refs_index_add_hpu_complex128",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref__refs_index_add_hpu_complex32",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref__refs_index_add_hpu_complex64",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref__refs_index_add_hpu_float16",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref__refs_index_add_hpu_float32",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref__refs_index_add_hpu_float64",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref__refs_index_add_hpu_int16",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref__refs_index_add_hpu_int32",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref__refs_index_add_hpu_int64",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref__refs_index_add_hpu_int8",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref__refs_index_add_hpu_uint8",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref__refs_index_copy_hpu_bfloat16",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref__refs_index_copy_hpu_bool",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref__refs_index_copy_hpu_complex128",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref__refs_index_copy_hpu_complex64",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref__refs_index_copy_hpu_float16",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref__refs_index_copy_hpu_float32",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref__refs_index_copy_hpu_float64",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref__refs_index_copy_hpu_int16",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref__refs_index_copy_hpu_int32",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref__refs_index_copy_hpu_int64",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref__refs_index_copy_hpu_int8",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref__refs_index_copy_hpu_uint8",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref__refs_index_fill_hpu_bfloat16",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref__refs_index_fill_hpu_bool",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref__refs_index_fill_hpu_complex128",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref__refs_index_fill_hpu_complex64",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref__refs_index_fill_hpu_float16",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref__refs_index_fill_hpu_float32",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref__refs_index_fill_hpu_float64",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref__refs_index_fill_hpu_int16",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref__refs_index_fill_hpu_int32",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref__refs_index_fill_hpu_int64",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref__refs_index_fill_hpu_int8",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref__refs_index_fill_hpu_uint8",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref__refs_index_select_hpu_bfloat16",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref__refs_index_select_hpu_bool",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref__refs_index_select_hpu_complex128",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref__refs_index_select_hpu_complex32",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref__refs_index_select_hpu_complex64",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref__refs_index_select_hpu_float16",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref__refs_index_select_hpu_float32",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref__refs_index_select_hpu_float64",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref__refs_index_select_hpu_int16",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref__refs_index_select_hpu_int32",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref__refs_index_select_hpu_int64",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref__refs_index_select_hpu_int8",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref__refs_index_select_hpu_uint8",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref__refs_linspace_hpu_int16",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref__refs_linspace_hpu_int32",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref__refs_linspace_hpu_int64",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref__refs_nn_functional_pdist_hpu_float32",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref__refs_nn_functional_pdist_hpu_float64",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref__refs_sub_hpu_complex32",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref__refs_tensor_split_hpu_bfloat16",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref__refs_tensor_split_hpu_bool",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref__refs_tensor_split_hpu_complex128",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref__refs_tensor_split_hpu_complex64",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref__refs_tensor_split_hpu_float16",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref__refs_tensor_split_hpu_float32",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref__refs_tensor_split_hpu_float64",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref__refs_tensor_split_hpu_int16",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref__refs_tensor_split_hpu_int32",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref__refs_tensor_split_hpu_int64",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref__refs_tensor_split_hpu_int8",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref__refs_tensor_split_hpu_uint8",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref__refs_trace_hpu_complex128",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref__refs_trace_hpu_complex64",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref__refs_trace_hpu_float32",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref__refs_trace_hpu_float64",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref__refs_trace_hpu_int16",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref__refs_trace_hpu_int32",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref__refs_trace_hpu_int64",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref__refs_trace_hpu_int8",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref__refs_trace_hpu_uint8",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref_errors__refs_cat_hpu",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref_errors__refs_clamp_max_hpu",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref_errors__refs_clamp_min_hpu",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref_errors__refs_hstack_hpu",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref_errors__refs_index_select_hpu",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref_errors__refs_maximum_hpu",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref_errors__refs_minimum_hpu",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref_errors__refs_vstack_hpu",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref_meta__refs_arange_hpu_int64",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref_meta__refs_narrow_hpu_bfloat16",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref_meta__refs_narrow_hpu_bool",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref_meta__refs_narrow_hpu_complex128",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref_meta__refs_narrow_hpu_complex32",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref_meta__refs_narrow_hpu_complex64",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref_meta__refs_narrow_hpu_float16",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref_meta__refs_narrow_hpu_float32",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref_meta__refs_narrow_hpu_float64",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref_meta__refs_narrow_hpu_int16",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref_meta__refs_narrow_hpu_int32",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref_meta__refs_narrow_hpu_int64",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref_meta__refs_narrow_hpu_int8",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref_meta__refs_narrow_hpu_uint8",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref_meta__refs_tensor_split_hpu_bfloat16",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref_meta__refs_tensor_split_hpu_bool",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref_meta__refs_tensor_split_hpu_complex128",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref_meta__refs_tensor_split_hpu_complex64",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref_meta__refs_tensor_split_hpu_float16",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref_meta__refs_tensor_split_hpu_float32",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref_meta__refs_tensor_split_hpu_float64",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref_meta__refs_tensor_split_hpu_int16",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref_meta__refs_tensor_split_hpu_int32",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref_meta__refs_tensor_split_hpu_int64",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref_meta__refs_tensor_split_hpu_int8",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref_meta__refs_tensor_split_hpu_uint8",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref_ops_nvprims_native_batch_norm_hpu_float32",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref_ops_nvprims_native_batch_norm_hpu_float64",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref_ops_nvprims_var_mean_hpu_bfloat16",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref_ops_nvprims_var_mean_hpu_float16",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref_ops_nvprims_var_mean_hpu_float32",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref_ops_nvprims_var_mean_hpu_float64",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref_torch_fallback__refs_abs_hpu_complex32",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref_torch_fallback__refs_linspace_hpu_int16",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref_torch_fallback__refs_linspace_hpu_int32",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref_torch_fallback__refs_linspace_hpu_int64",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_python_ref_torch_fallback__refs_sub_hpu_complex32",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_variant_consistency_eager_addcdiv_hpu_complex64",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_variant_consistency_eager_addcdiv_hpu_float32",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_variant_consistency_eager_addcmul_hpu_complex64",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_variant_consistency_eager_addcmul_hpu_float32",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_variant_consistency_eager_arange_hpu_float32",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_variant_consistency_eager_chalf_hpu_complex64",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_variant_consistency_eager_chalf_hpu_float32",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_variant_consistency_eager_ldexp_hpu_complex64",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_variant_consistency_eager_ldexp_hpu_float32",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_variant_consistency_eager_linspace_hpu_complex64",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_variant_consistency_eager_linspace_hpu_float32",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_variant_consistency_eager_logspace_hpu_complex64",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_variant_consistency_eager_logspace_hpu_float32",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_variant_consistency_eager_ones_hpu_complex64",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_variant_consistency_eager_ones_hpu_float32",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_variant_consistency_eager_randn_hpu_complex64",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_variant_consistency_eager_randn_hpu_float32",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_variant_consistency_eager_uniform_hpu_complex64",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_variant_consistency_eager_uniform_hpu_float32",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_variant_consistency_eager_zeros_hpu_complex64",
        pt_dir + "/test/test_ops.py::TestCommonHPU::test_variant_consistency_eager_zeros_hpu_float32",
        pt_dir + "/test/test_ops.py::TestCompositeComplianceHPU::test_backward_index_reduce_hpu_float32",
        pt_dir + "/test/test_ops.py::TestCompositeComplianceHPU::test_backward_istft_hpu_float32",
        pt_dir + "/test/test_ops.py::TestCompositeComplianceHPU::test_backward_narrow_hpu_float32",
        pt_dir
        + "/test/test_ops.py::TestCompositeComplianceHPU::test_backward_nn_functional_gaussian_nll_loss_hpu_float32",
        pt_dir + "/test/test_ops.py::TestCompositeComplianceHPU::test_backward_scatter_reduce_prod_hpu_float32",
        pt_dir + "/test/test_ops.py::TestCompositeComplianceHPU::test_backward_tensor_split_hpu_float32",
        pt_dir + "/test/test_ops.py::TestCompositeComplianceHPU::test_forward_ad_narrow_hpu_float32",
        pt_dir
        + "/test/test_ops.py::TestCompositeComplianceHPU::test_forward_ad_nn_functional_gaussian_nll_loss_hpu_float32",
        pt_dir
        + "/test/test_ops.py::TestCompositeComplianceHPU::test_forward_ad_nn_functional_max_unpool1d_hpu_float32",
        pt_dir
        + "/test/test_ops.py::TestCompositeComplianceHPU::test_forward_ad_nn_functional_max_unpool3d_hpu_float32",
        pt_dir + "/test/test_ops.py::TestCompositeComplianceHPU::test_forward_ad_tensor_split_hpu_float32",
        pt_dir + "/test/test_ops.py::TestCompositeComplianceHPU::test_operator_narrow_hpu_float32",
        pt_dir
        + "/test/test_ops.py::TestCompositeComplianceHPU::test_operator_nn_functional_gaussian_nll_loss_hpu_float32",
        pt_dir + "/test/test_ops.py::TestCompositeComplianceHPU::test_operator_tensor_split_hpu_float32",
        pt_dir + "/test/test_ops.py::TestMathBitsHPU::test_conj_view__refs_linspace_hpu_complex64",
        pt_dir + "/test/test_ops.py::TestMathBitsHPU::test_conj_view__refs_logspace_hpu_complex64",
        pt_dir + "/test/test_ops.py::TestMathBitsHPU::test_conj_view__refs_ones_hpu_complex64",
        pt_dir + "/test/test_ops.py::TestMathBitsHPU::test_conj_view__refs_zeros_hpu_complex64",
        pt_dir + "/test/test_ops.py::TestMathBitsHPU::test_conj_view_cartesian_prod_hpu_complex64",
        pt_dir + "/test/test_ops.py::TestMathBitsHPU::test_conj_view_chalf_hpu_complex64",
        pt_dir + "/test/test_ops.py::TestMathBitsHPU::test_conj_view_ldexp_hpu_complex64",
        pt_dir + "/test/test_ops.py::TestMathBitsHPU::test_conj_view_linspace_hpu_complex64",
        pt_dir + "/test/test_ops.py::TestMathBitsHPU::test_conj_view_logspace_hpu_complex64",
        pt_dir + "/test/test_ops.py::TestMathBitsHPU::test_conj_view_narrow_hpu_complex64",
        pt_dir + "/test/test_ops.py::TestMathBitsHPU::test_conj_view_ones_hpu_complex64",
        pt_dir + "/test/test_ops.py::TestMathBitsHPU::test_conj_view_randn_hpu_complex64",
        pt_dir + "/test/test_ops.py::TestMathBitsHPU::test_conj_view_stack_hpu_complex64",
        pt_dir + "/test/test_ops.py::TestMathBitsHPU::test_conj_view_sum_to_size_hpu_complex64",
        pt_dir + "/test/test_ops.py::TestMathBitsHPU::test_conj_view_uniform_hpu_complex64",
        pt_dir + "/test/test_ops.py::TestMathBitsHPU::test_conj_view_zeros_hpu_complex64",
        pt_dir + "/test/test_ops.py::TestMathBitsHPU::test_neg_conj_view__refs_linspace_hpu_complex128",
        pt_dir + "/test/test_ops.py::TestMathBitsHPU::test_neg_conj_view__refs_logspace_hpu_complex128",
        pt_dir + "/test/test_ops.py::TestMathBitsHPU::test_neg_conj_view__refs_ones_hpu_complex128",
        pt_dir + "/test/test_ops.py::TestMathBitsHPU::test_neg_conj_view__refs_zeros_hpu_complex128",
        pt_dir + "/test/test_ops.py::TestMathBitsHPU::test_neg_conj_view_chalf_hpu_complex128",
        pt_dir + "/test/test_ops.py::TestMathBitsHPU::test_neg_conj_view_ldexp_hpu_complex128",
        pt_dir + "/test/test_ops.py::TestMathBitsHPU::test_neg_conj_view_linspace_hpu_complex128",
        pt_dir + "/test/test_ops.py::TestMathBitsHPU::test_neg_conj_view_logspace_hpu_complex128",
        pt_dir + "/test/test_ops.py::TestMathBitsHPU::test_neg_conj_view_ones_hpu_complex128",
        pt_dir + "/test/test_ops.py::TestMathBitsHPU::test_neg_conj_view_randn_hpu_complex128",
        pt_dir + "/test/test_ops.py::TestMathBitsHPU::test_neg_conj_view_uniform_hpu_complex128",
        pt_dir + "/test/test_ops.py::TestMathBitsHPU::test_neg_conj_view_zeros_hpu_complex128",
        pt_dir + "/test/test_ops.py::TestMathBitsHPU::test_neg_view__refs_arange_hpu_float64",
        pt_dir + "/test/test_ops.py::TestMathBitsHPU::test_neg_view__refs_linspace_hpu_float64",
        pt_dir + "/test/test_ops.py::TestMathBitsHPU::test_neg_view__refs_logspace_hpu_float64",
        pt_dir + "/test/test_ops.py::TestMathBitsHPU::test_neg_view__refs_ones_hpu_float64",
        pt_dir + "/test/test_ops.py::TestMathBitsHPU::test_neg_view__refs_zeros_hpu_float64",
        pt_dir + "/test/test_ops.py::TestMathBitsHPU::test_neg_view_arange_hpu_float64",
        pt_dir + "/test/test_ops.py::TestMathBitsHPU::test_neg_view_cartesian_prod_hpu_float64",
        pt_dir + "/test/test_ops.py::TestMathBitsHPU::test_neg_view_chalf_hpu_float64",
        pt_dir + "/test/test_ops.py::TestMathBitsHPU::test_neg_view_ldexp_hpu_float64",
        pt_dir + "/test/test_ops.py::TestMathBitsHPU::test_neg_view_linspace_hpu_float64",
        pt_dir + "/test/test_ops.py::TestMathBitsHPU::test_neg_view_logspace_hpu_float64",
        pt_dir + "/test/test_ops.py::TestMathBitsHPU::test_neg_view_narrow_hpu_float64",
        pt_dir + "/test/test_ops.py::TestMathBitsHPU::test_neg_view_ones_hpu_float64",
        pt_dir + "/test/test_ops.py::TestMathBitsHPU::test_neg_view_randn_hpu_float64",
        pt_dir + "/test/test_ops.py::TestMathBitsHPU::test_neg_view_stack_hpu_float64",
        pt_dir + "/test/test_ops.py::TestMathBitsHPU::test_neg_view_sum_to_size_hpu_float64",
        pt_dir + "/test/test_ops.py::TestMathBitsHPU::test_neg_view_uniform_hpu_float64",
        pt_dir + "/test/test_ops.py::TestMathBitsHPU::test_neg_view_zeros_hpu_float64",
        pt_dir
        + "/test/test_ops.py::TestCompositeComplianceHPU::test_forward_ad_nn_functional_max_unpool3d_hpu_float32",
        pt_dir + "/test/test_ops.py::TestCompositeComplianceHPU::test_operator_narrow_hpu_float32",
        pt_dir
        + "/test/test_ops.py::TestCompositeComplianceHPU::test_operator_nn_functional_gaussian_nll_loss_hpu_float32",
        pt_dir + "/test/test_ops.py::TestCompositeComplianceHPU::test_operator_tensor_split_hpu_float32",
    ]
}

all_test = [cpu_failed_tests_to_skip]
all_cpu_failed_dict = {}
for test_dict in all_test:
    temp_dict = {node_id: jira for jira in test_dict for node_id in test_dict[jira]}
    all_cpu_failed_dict = {**all_cpu_failed_dict, **temp_dict}


def displayskipcount():
    print("TC Failed in CPU ")
    for key in cpu_failed_tests_to_skip.keys():
        print(key, " : ", len(cpu_failed_tests_to_skip[key]))


def main():
    displayskipcount()


if __name__ == "__main__":
    main()
